apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- local-community-operators.yml
- local-certified-operators.yml

configurations: 
- configuration.yaml

configMapGenerator:
- name: marketplace-properties
  envs: [marketplace.properties]
  
generatorOptions:
 disableNameSuffixHash: true

namespace: openshift-marketplace

vars:
- name: REGISTRY
  objref: { kind: ConfigMap, name: marketplace-properties, apiVersion: v1 }
  fieldref: { fieldpath: data.REGISTRY }
- name: RH_CATALOG_VERSION
  objref: { kind: ConfigMap, name: marketplace-properties, apiVersion: v1 }
  fieldref: { fieldpath: data.RH_CATALOG_VERSION }
