{{- if .Values.CatalogSource.include }}

---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: local-community-operators2
  namespace: openshift-marketplace
spec:
  displayName: Local Community Operator Catalog
  image: {{ .Values.Cluster.registry }}/redhat/community-operator-index:{{ .Values.CatalogSource.rh_catalog_version }}
  publisher: grpc
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 1440m

{{ end }}