apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/openshift-marketplace

configMapGenerator:
  - name: marketplace-properties
    namespace: openshift-marketplace
    envs: [marketplace.properties]
    behavior: replace

generatorOptions:
 annotations:
   config.kubernetes.io/local-config: 'true'
