---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- all.yaml

configMapGenerator:
  - name: cluster-monitoring-config
    namespace: openshift-monitoring
    files:
      - config.yaml=data/openshift-monitoring/cluster-monitoring-config.data
